//! Regenerates `website/src/content/docs/reference/indicators.md` from the
//! indicator registry in `src/indicators/mod.rs`. CI runs this and diffs
//! against HEAD to catch drift when indicators are added/renamed.
//!
//! Screenshots are rendered separately by `scripts/gen_screenshots.sh` and
//! referenced by filename here — missing PNGs are silently skipped so CI
//! doesn't need to generate images.
//!
//! Usage: `cargo run --example gen_docs`

use chartgen::indicators::{registry, IndicatorInfo};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

const OUTPUT: &str = "website/src/content/docs/reference/indicators.md";
const SCREENSHOT_DIR: &str = "website/src/assets/indicators";
const SCREENSHOT_REF: &str = "../../../assets/indicators";

fn main() {
    let entries = registry();

    let overlays: Vec<_> = entries.iter().filter(|e| e.category == "overlay").collect();
    let panels: Vec<_> = entries.iter().filter(|e| e.category == "panel").collect();
    let external: Vec<_> = entries
        .iter()
        .filter(|e| e.category == "external")
        .collect();

    let mut out = String::new();
    out.push_str(
        "---\n\
         title: Indicators\n\
         description: Every registered indicator with a sample rendering.\n\
         ---\n\
         \n\
         <!-- Generated by `cargo run --example gen_docs`. Do not edit by hand. -->\n\
         \n\
         Indicators live in three buckets in the registry (`src/indicators/mod.rs`):\n\
         \n\
         - **Overlays** draw on the price chart (bands, clouds, volume profiles).\n\
         - **Panels** render as separate rows below the price chart (oscillators, volume).\n\
         - **External** pull from third-party APIs (Binance derivatives, alternative.me).\n\
         \n\
         Every name and every alias below is accepted by the CLI (`-p <name>`) and by\n\
         the `generate_chart` MCP tool's `indicators` parameter. Screenshots are\n\
         rendered from `AAPL` daily data (overlays and panels) and `BTCUSDT` daily\n\
         data (external) — regenerate with `./scripts/gen_screenshots.sh`.\n\
         \n",
    );

    push_section(&mut out, "Overlays", &overlays);
    push_section(&mut out, "Panels", &panels);
    push_section(&mut out, "External", &external);

    out.push_str(
        "## Parameter examples (MCP)\n\
         \n\
         ```json\n\
         {\"name\": \"rsi\", \"length\": 21}\n\
         {\"name\": \"bbands\", \"length\": 30, \"mult\": 2.5}\n\
         {\"name\": \"volume_profile\", \"bins\": 32, \"side\": \"right\"}\n\
         ```\n\
         \n\
         Call the `list_indicators` MCP tool for the authoritative list with each\n\
         indicator's description, default parameters, and category at runtime.\n",
    );

    let path = Path::new(OUTPUT);
    fs::write(path, &out).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    println!(
        "wrote {} ({} overlays, {} panels, {} external)",
        path.display(),
        overlays.len(),
        panels.len(),
        external.len()
    );
}

fn push_section(out: &mut String, heading: &str, entries: &[&IndicatorInfo]) {
    out.push_str(&format!("## {heading}\n\n"));
    out.push_str("### Summary\n\n");
    out.push_str("| Name | Aliases |\n|------|---------|\n");
    for e in entries {
        let aliases = if e.aliases.is_empty() {
            String::new()
        } else {
            e.aliases
                .iter()
                .map(|a| format!("`{a}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| [`{}`](#{}) | {} |\n",
            e.name,
            anchor(e.name),
            aliases
        ));
    }
    out.push('\n');

    for e in entries {
        push_entry(out, e);
    }
}

fn push_entry(out: &mut String, e: &IndicatorInfo) {
    out.push_str(&format!("### `{}`\n\n", e.name));

    let desc = e.description.trim();
    if !desc.is_empty() {
        out.push_str(desc);
        out.push_str("\n\n");
    }

    if !e.aliases.is_empty() {
        let aliases = e
            .aliases
            .iter()
            .map(|a| format!("`{a}`"))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("**Aliases:** {aliases}\n\n"));
    }

    if let Some(params_md) = render_params(&e.params) {
        out.push_str("**Parameters:**\n\n");
        out.push_str(&params_md);
        out.push('\n');
    }

    if let Some(img) = screenshot_ref(e.name) {
        out.push_str(&format!("![{} sample render]({})\n\n", e.name, img));
    }
}

fn render_params(params: &Value) -> Option<String> {
    let arr = params.as_array()?;
    if arr.is_empty() {
        return None;
    }
    let mut s = String::new();
    s.push_str(
        "| Param | Type | Default | Description |\n|-------|------|---------|-------------|\n",
    );
    for item in arr {
        let name = item.get("name").and_then(|v| v.as_str()).unwrap_or("");
        let ty = item.get("type").and_then(|v| v.as_str()).unwrap_or("");
        let default = item
            .get("default")
            .map(format_value)
            .unwrap_or_else(String::new);
        let desc = item
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        s.push_str(&format!("| `{name}` | `{ty}` | `{default}` | {desc} |\n"));
    }
    Some(s)
}

fn format_value(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

fn screenshot_ref(name: &str) -> Option<String> {
    let path = PathBuf::from(SCREENSHOT_DIR).join(format!("{name}.png"));
    if path.exists() {
        Some(format!("{SCREENSHOT_REF}/{name}.png"))
    } else {
        None
    }
}

fn anchor(name: &str) -> String {
    // Starlight's heading autolinks use lowercased, underscore-preserving slugs.
    // `rsi_mfi_stoch` heading → `#rsi_mfi_stoch` anchor.
    name.to_lowercase()
}
