//! Regenerates `website/src/content/docs/reference/indicators.md` from the
//! indicator registry in `src/indicators/mod.rs`. CI runs this and diffs
//! against HEAD to catch drift when indicators are added/renamed.
//!
//! Usage: `cargo run --example gen_docs`

use chartgen::indicators::{registry, IndicatorInfo};
use std::fs;
use std::path::Path;

const OUTPUT: &str = "website/src/content/docs/reference/indicators.md";

fn main() {
    let entries = registry();

    let overlays: Vec<_> = entries.iter().filter(|e| e.category == "overlay").collect();
    let panels: Vec<_> = entries.iter().filter(|e| e.category == "panel").collect();
    let external: Vec<_> = entries
        .iter()
        .filter(|e| e.category == "external")
        .collect();

    let mut out = String::new();
    out.push_str(
        "---\n\
         title: Indicators\n\
         description: All registered indicators, grouped by how they render.\n\
         ---\n\
         \n\
         <!-- Generated by `cargo run --example gen_docs`. Do not edit by hand. -->\n\
         \n\
         Indicators live in three buckets in the registry (`src/indicators/mod.rs`):\n\
         \n\
         - **Overlays** draw on the price chart (bands, clouds, volume profiles).\n\
         - **Panels** render as separate rows below the price chart (oscillators, volume).\n\
         - **External** pull from third-party APIs (Binance derivatives, alternative.me).\n\
         \n\
         Every name and every alias below is accepted by the CLI (`-p <name>`) and by\n\
         the `generate_chart` MCP tool's `indicators` parameter.\n\
         \n",
    );

    push_section(&mut out, "Overlays", &overlays);
    push_section(&mut out, "Panels", &panels);
    push_section(&mut out, "External", &external);

    out.push_str(
        "## Parameter examples (MCP)\n\
         \n\
         ```json\n\
         {\"name\": \"rsi\", \"length\": 21}\n\
         {\"name\": \"bbands\", \"length\": 30, \"mult\": 2.5}\n\
         {\"name\": \"volume_profile\", \"bins\": 32, \"side\": \"right\"}\n\
         ```\n\
         \n\
         Call the `list_indicators` MCP tool for the authoritative list with each\n\
         indicator's description, default parameters, and category at runtime.\n",
    );

    let path = Path::new(OUTPUT);
    fs::write(path, &out).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    println!(
        "wrote {} ({} overlays, {} panels, {} external)",
        path.display(),
        overlays.len(),
        panels.len(),
        external.len()
    );
}

fn push_section(out: &mut String, heading: &str, entries: &[&IndicatorInfo]) {
    out.push_str(&format!("## {heading}\n\n"));
    out.push_str("| Name | Aliases |\n|------|---------|\n");
    for e in entries {
        let aliases = if e.aliases.is_empty() {
            String::new()
        } else {
            e.aliases
                .iter()
                .map(|a| format!("`{a}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!("| `{}` | {} |\n", e.name, aliases));
    }
    out.push('\n');
}
